#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives two directories below the base directory.
BASE_DIR="$( cd $MY_DIR/../.. && pwd )"

# And that a directory called 'notes' is a peer of the base directory.
NOTES_DIR="$( cd $BASE_DIR/../notes && pwd )"

mkdir -p "${BASE_DIR}/source/posts"
cp -r "${NOTES_DIR}"/* "${BASE_DIR}/source/posts"

pushd ${BASE_DIR}
  bundle
  bundle exec middleman build --clean
popd
