#!/bin/bash

set -eux

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives two directories below the base directory.
base_dir="$( cd "${my_dir}/../.." && pwd )"

# And that a directory called 'notes' is a peer of the base directory.
notes_dir="$( cd "${base_dir}/../notes" && pwd )"

mkdir -p "${base_dir}/source/posts"
cp -r "${notes_dir}"/* "${base_dir}/source/posts"

pushd "${base_dir}"
  bundle
  bundle exec middleman build --clean
popd
