---
resources:
- name: app-develop
  type: git
  source:
    uri: git@github.com:robdimsdale/notes-app
    branch: develop
    private_key: {{app-private-key}}

- name: app-master
  type: git
  source:
    uri: git@github.com:robdimsdale/notes-app
    branch: master
    private_key: {{app-private-key}}

- name: notes
  type: git
  source:
    uri: {{notes-git-uri}}
    branch: {{notes-git-branch}}
    private_key: {{notes-private-key}}

- name: slack_alert
  type: slack-notification
  source:
    url: {{slack-url}}

jobs:
- name: build-deploy-site-develop
  public: false
  serial: true
  plan:
  - aggregate:
    - get: notes
      trigger: true
    - get: app
      resource: app-develop
      trigger: true
  - task: build-deploy-site-develop
    file: app/scripts/ci/build_deploy_site_develop.yml
    config:
      params:
        CF_USER: {{cf-user}}
        CF_PASSWORD: {{cf-password}}
        CF_ORG: {{cf-org-develop}}
        CF_SPACE: {{cf-space-develop}}
        CF_APPLICATION: {{cf-application-develop}}
        STATIC_FILE_AUTH: {{static-file-auth-develop}}
    on_success:
      put: slack_alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{slack-develop-success-text}}
    on_failure:
      put: slack_alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{slack-develop-failure-text}}

- name: build-deploy-site-master
  public: false
  serial: true
  plan:
  - aggregate:
    - get: notes
      trigger: true
    - get: app
      resource: app-master
      trigger: true
  - task: build-deploy-site-master
    file: app/scripts/ci/build_deploy_site_master.yml
    config:
      params:
        CF_USER: {{cf-user}}
        CF_PASSWORD: {{cf-password}}
        CF_ORG: {{cf-org-master}}
        CF_SPACE: {{cf-space-master}}
        CF_APPLICATION: {{cf-application-master}}
        STATIC_FILE_AUTH: {{static-file-auth-master}}
    on_success:
      put: slack_alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{slack-master-success-text}}
    on_failure:
      put: slack_alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{slack-master-failure-text}}
